### ISSUE TITLE
developへpush時にtest環境へデプロイされない

### ISSUE THREAD

**Issue by RikitoNoto** [RikitoNoto/gmo-fx-py#68]
自動リリース処理でdevelopブランチにpushされた場合に自動リリースされるようにしている
```yaml
on:
  push:
    branches:
      - develop
    paths:
      - setup.py
```
しかし、仕様上botがpushしたものはトリガとして判定されないため、リリースされない。

```version_up_setuppy.yaml```からリリース処理を呼び出すようにして自動でリリースされるようにする
